import type { Camera, PlaceholderImage } from '@/lib/definitions';

export const cameras: Camera[] = [
  {
    id: '1',
    name: 'Sony Alpha a7 IV',
    slug: 'sony-alpha-a7-iv',
    shortDescription: 'The hybrid standard. Pushing beyond full-frame, for stills and movies.',
    price: 2499,
    specs: {
      sensor: '35mm full-frame Exmor R CMOS sensor',
      megapixels: '33.0MP',
      iso: '100-51200 (expandable to 50-204800)',
      video: '4K 60p, 10-bit 4:2:2',
      autofocus: '759 points (phase-detection AF)',
      connectivity: 'Wi-Fi, Bluetooth, USB-C, HDMI',
    },
    bestFor: ['Photography', 'Videography', 'Professional'],
  },
  {
    id: '2',
    name: 'Sony Alpha a6400',
    slug: 'sony-alpha-a6400',
    shortDescription: 'Compact and capable, with leading-edge autofocus and subject tracking.',
    price: 899,
    specs: {
      sensor: 'APS-C type Exmor CMOS sensor',
      megapixels: '24.2MP',
      iso: '100-32000 (expandable to 102400)',
      video: '4K 30p',
      autofocus: '425 points (phase-detection AF)',
      connectivity: 'Wi-Fi, Bluetooth, Micro USB',
    },
    bestFor: ['Photography', 'Vlogging'],
  },
  {
    id: '3',
    name: 'Sony Alpha a6700',
    slug: 'sony-alpha-a6700',
    shortDescription: 'AI-powered autofocus meets stunning image quality in a compact body.',
    price: 1399,
    specs: {
      sensor: 'APS-C type Exmor R CMOS sensor',
      megapixels: '26.0MP',
      iso: '100-32000 (expandable to 50-102400)',
      video: '4K 120p, 10-bit 4:2:2',
      autofocus: '759 points with AI processing unit',
      connectivity: 'Wi-Fi, Bluetooth, USB-C',
    },
    bestFor: ['Photography', 'Videography'],
  },
  {
    id: '4',
    name: 'Sony FX30',
    slug: 'sony-fx30',
    shortDescription: 'The cinematic look, accessible. A new step into the world of filmmaking.',
    price: 1799,
    specs: {
      sensor: 'APS-C type Exmor R CMOS sensor',
      megapixels: '20.1MP (video), 26.0MP (stills)',
      iso: '100-32000 (Dual Base ISO)',
      video: '4K 120p, 10-bit 4:2:2',
      autofocus: 'Fast Hybrid AF with cinematic tracking',
      connectivity: 'Wi-Fi, Bluetooth, USB-C, XLR Handle Unit',
    },
    bestFor: ['Videography', 'Professional'],
  },
  {
    id: '5',
    name: 'Sony ZV-E10',
    slug: 'sony-zv-e10',
    shortDescription: 'Made for vlogging, with interchangeable lenses and creative control.',
    price: 699,
    specs: {
      sensor: 'APS-C type Exmor CMOS sensor',
      megapixels: '24.2MP',
      iso: '100-32000',
      video: '4K 30p',
      autofocus: 'Real-time Eye AF, Product Showcase Setting',
      connectivity: 'Wi-Fi, Bluetooth, USB-C',
    },
    bestFor: ['Vlogging'],
  },
];

export const placeholderImages: PlaceholderImage[] = [
  {
    id: 'hero-banner',
    description: 'A close-up of a modern Sony camera lens, highlighting its intricate design and glass elements.',
    imageUrl: 'https://picsum.photos/seed/hero-banner/1920/1080',
    imageHint: 'camera lens',
    gallery: [],
  },
  {
    id: 'sony-alpha-a7-iv',
    description: 'The Sony Alpha a7 IV camera body shown from the front three-quarter angle.',
    imageUrl: 'https://picsum.photos/seed/a7iv-main/800/600',
    imageHint: 'sony camera',
    gallery: [
      { id: '1', imageUrl: 'https://picsum.photos/seed/a7iv-1/1200/800', imageHint: 'camera angle' },
      { id: '2', imageUrl: 'https://picsum.photos/seed/a7iv-2/1200/800', imageHint: 'camera back' },
      { id: '3', imageUrl: 'https://picsum.photos/seed/a7iv-3/1200/800', imageHint: 'camera top' },
    ],
  },
  {
    id: 'sony-alpha-a6400',
    description: 'The compact Sony Alpha a6400 camera body with its screen flipped up for vlogging.',
    imageUrl: 'https://picsum.photos/seed/a6400-main/800/600',
    imageHint: 'sony camera',
    gallery: [
      { id: '1', imageUrl: 'https://picsum.photos/seed/a6400-1/1200/800', imageHint: 'camera front' },
      { id: '2', imageUrl: 'https://picsum.photos/seed/a6400-2/1200/800', imageHint: 'camera side' },
      { id: '3', imageUrl: 'https://picsum.photos/seed/a6400-3/1200/800', imageHint: 'camera lifestyle' },
    ],
  },
  {
    id: 'sony-alpha-a6700',
    description: 'The powerful Sony Alpha a6700 camera shown in a dynamic outdoor setting.',
    imageUrl: 'https://picsum.photos/seed/a6700-main/800/600',
    imageHint: 'sony camera',
    gallery: [
      { id: '1', imageUrl: 'https://picsum.photos/seed/a6700-1/1200/800', imageHint: 'camera detail' },
      { id: '2', imageUrl: 'https://picsum.photos/seed/a6700-2/1200/800', imageHint: 'camera sensor' },
      { id: '3', imageUrl: 'https://picsum.photos/seed/a6700-3/1200/800', imageHint: 'camera action' },
    ],
  },
  {
    id: 'sony-fx30',
    description: 'The Sony FX30 cinema camera rigged for a professional video shoot.',
    imageUrl: 'https://picsum.photos/seed/fx30-main/800/600',
    imageHint: 'cinema camera',
    gallery: [
      { id: '1', imageUrl: 'https://picsum.photos/seed/fx30-1/1200/800', imageHint: 'camera rig' },
      { id: '2', imageUrl: 'https://picsum.photos/seed/fx30-2/1200/800', imageHint: 'camera on set' },
      { id: '3', imageUrl: 'https://picsum.photos/seed/fx30-3/1200/800', imageHint: 'camera operator' },
    ],
  },
  {
    id: 'sony-zv-e10',
    description: 'The Sony ZV-E10 vlogging camera held in hand, ready to record.',
    imageUrl: 'https://picsum.photos/seed/zve10-main/800/600',
    imageHint: 'vlogging camera',
    gallery: [
      { id: '1', imageUrl: 'https://picsum.photos/seed/zve10-1/1200/800', imageHint: 'camera lifestyle' },
      { id: '2', imageUrl: 'https://picsum.photos/seed/zve10-2/1200/800', imageHint: 'camera screen' },
      { id: '3', imageUrl: 'https://picsum.photos/seed/zve10-3/1200/800', imageHint: 'camera vlogger' },
    ],
  },
  {
    id: 'about-1',
    description: 'Image showcasing Sony\'s sensor technology.',
    imageUrl: 'https://picsum.photos/seed/about1/600/400',
    imageHint: 'camera sensor',
    gallery: [],
  },
  {
    id: 'about-2',
    description: 'Image highlighting Sony\'s autofocus capabilities.',
    imageUrl: 'https://picsum.photos/seed/about2/600/400',
    imageHint: 'camera autofocus',
    gallery: [],
  },
];
